development:
  adapter: postgresql
  encoding: unicode
  database: mango_api_dev
  pool: 5
  host: localhost
  username: ''
  password: ''

test:
  adapter: postgresql
  encoding: unicode
  database: mango_api_test
  pool: 5
  username: ''
  password: ''

  production:
    adapter: postgresql
    encoding: unicode
    pool: 5
    database: <%= ENV['RDS_DB_NAME'] %>
    username: <%= ENV['RDS_USERNAME'] %>
    password: <%= ENV['RDS_PASSWORD'] %>
    host: <%= ENV['RDS_HOSTNAME'] %>
    port: <%= ENV['RDS_PORT'] %>